[package]
name = "sipbot"
version = "0.1.1"
edition = "2024"
authors = ["jinti<shenjindi@fourz.cn>"]
repository = "https://github.com/miuda-ai/sipbot"
description = "A simple SIP bot with RTP"
readme = "README.md"
keywords = ["rtp", "srtp", "sip", "cli"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
toml = "0.9.8"
tracing = "0.1"
anyhow = "1.0"
rsipstack = "0.2.94"
rsip = "0.4.0"
tokio-util = "0.7"
rustrtc = "0.2.10"
#rustrtc = { path = "../rustrtc" }
voice-engine = "0.3.20"
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4.42"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "chrono"] }
hound = "3.5.1"
bytes = "1.11.0"
rubato = "0.16.2"

[profile.release]
opt-level = "z"
lto = true
strip = "symbols"
